services:
    pierre_durand_encrypter:
        class: PierreDurand\EncrypterBundle\Util\Encrypter
        arguments: ["%pierre_durand_encrypter.key%", "%pierre_durand_encrypter.cipher%", "%pierre_durand_encrypter.mode%"]