services:
    pierrre_encrypter.twig_extension:
        class: Pierrre\EncrypterBundle\Twig\Extension\EncrypterExtension
        arguments: ["@pierrre_encrypter.manager", "%pierrre_encrypter.twig.default_encrypter%"]
        tags:
            - { name: twig.extension }