services:

    pierrre.twig_extension_encrypter:
        class: Pierrre\EncrypterBundle\Twig\Extension\Encrypter
        arguments: ["@pierrre_encrypter_manager"]
        tags:
            - { name: twig.extension }